[project]
name = "sbmlsim"
authors = [{name = "Philip W Fowler", email = "philip.fowler@ndm.ox.ac.uk"}]
license = {file = "LICENSE"}
readme = "README.md"
dynamic = ["version", "description"]
requires-python = ">=3.10"
dependencies = [
  "gumpy>=1.2.4",
  "numpy>=1.25.2",
  "pytest>=7.1.1"
]